name = "Hugo App"
license = "MIT"
licenselink = "https://github.com/devcows/hugo-app-theme/blob/master/LICENSE"
description = "A port of the Hugo App theme"
homepage = "//github.com/devcows/hugo-app-theme"
tags = ["docs", "company", "portfolio", "projects", "minimal", "responsive"]
features = ["docs", "themes", "disqus", "minimal", "responsive"]
min_version = 0.15

[author]
    name = "adrianmo"
    homepage = "//github.com/adrianmo"

# If Porting existing theme
[original]
    author =  "bootstrapious"
    homepage = "http://bootstrapious.com/p/universal-business-e-commerce-template"
